# Generated by Django 5.1.1 on 2024-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_lowStock',
            field=models.IntegerField(default=10),
        ),
    ]
