# Generated by Django 5.1.1 on 2024-12-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_item_related_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Proportion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Related_item',
        ),
    ]
